name: Build Release

on:
  release:
    types:
      - published

env:
  IMAGE_NAME: preflight

jobs:
  build-release:
    name: Build and push tag images
    strategy: 
      matrix:
        architecture: [amd64,ppc64le,arm64,s390x]
        platform: [linux]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ secrets.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: ${{ env.GITHUB_REF }}-${{ matrix.platform }}-${{ matrix.architecture }}
        archs: ${{ matrix.architecture }}
        build-args: |
          release_tag=${{env.GITHUB_REF }}
          ARCH=${{ matrix.architecture }}
        dockerfiles: |
          ./Dockerfile

    - name: Push Image
      id: push-image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.GITHUB_REF }}-${{ matrix.platform }}-${{ matrix.architecture }}
        registry: ${{ secrets.IMAGE_REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-image.outputs.registry-paths }}"

    outputs:
      imageName: ${{ env.IMAGE_NAME }}
      imageVersion: ${{ env.GITHUB_REF }}

  build-multiarch:
    needs: build-release
    uses: ./.github/workflows/build-multiarch.yml
    with:
      name: ${{ needs.build-release.outputs.imageName }}
      tag: ${{ needs.build-release.outputs.imageVersion }}
    secrets:
      registry: ${{ secrets.IMAGE_REGISTRY }}
      user: ${{ secrets.REGISTRY_USER }}
      password: ${{ secrets.REGISTRY_PASSWORD }}

  extract-assets:
    needs: build-release
    uses: ./.github/workflows/release-artifacts.yml

    with:
      name: ${{ needs.build-release.outputs.imageName }}
      tag: ${{ needs.build-release.outputs.imageVersion }}
    secrets:
      registry: ${{ secrets.IMAGE_REGISTRY }}
      token: ${{ secrets.GITHUB_TOKEN }}
