
name: Gemini AI Code Review

on:
  pull_request_target:
    branches:
      - main

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Gemini AI Code Review
        uses: sshnaidm/gemini-code-review-action@d4ccdaf0e2cad5cb79f80f6db07857c0e7fff28f
        with:
          gemini-key: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            Please review this code with focus on:
            - Security vulnerabilities
            - Adherence to best practices
            - Performance optimizations
            - Idiomatic Go
            Provide specific feedback and suggestions for improvement.
          model: 'gemini-2.5-pro'
