name: Create Release Artifacts

on:
  release:
    types:
      - created
  push:
    branches: [ ghactions ]

env:
  IMAGE_NAME: preflight

jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ linux ]
        architecture:
          - amd64
          - arm64
          - ppc64le
          - s390x
    steps:
    - name: Set Env Tags
      run: echo RELEASE_TAG=$(echo $GITHUB_REF | cut -d '/' -f 3) >> $GITHUB_ENV

    - name: Extract executable
      uses: shrink/actions-docker-extract@v1
      id: extract
      with:
        image: ${{ secrets.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_TAG }}-${{ matrix.platform }}-${{ matrix.architecture }}
        path: /usr/local/bin/preflight

    - name: Rename the binary
      run: |
        mv ${{ steps.extract.outputs.destination }}/preflight ${{ steps.extract.outputs.destination }}/preflight-${{ matrix.platform }}-${{ matrix.architecture }}

    - name: Upload binaries to the release
      uses: AButler/upload-release-assets@v2.0
      id: upload-release-asset
      with:
        files: ${{ steps.extract.outputs.destination }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
