name: Create Release Artifacts

on:
  release:
    types:
      - created
  push:
    branches: [ ghactions ]

jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux ]
        goarch: 
          - amd64
          - arm64
          - ppc64le
          - s390x
    steps:

    - name: code checkout
      uses: actions/checkout@v3

    - name: Set Env Tags
      run: echo RELEASE_TAG=$(echo $GITHUB_REF | cut -d '/' -f 3) >> $GITHUB_ENV

    - name: Go Release Action
      uses: bcrochet/go-release-action@optional-compression
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.17
        build_command: make build BINARY=preflight-${{ matrix.goos }}-${{ matrix.goarch }}
        binary_name: preflight-${{ matrix.goos }}-${{ matrix.goarch }}
        asset_name: preflight-${{ matrix.goos}}-${{ matrix.goarch}}
        compress_assets: false
        md5sum: false
        sha256sum: true
